
export const labels:{ [key: string]: string } = {
  email:"Email",
  password: "Password",
  enter: "Enter",
  confirmPassword: "Confirm Password",
  getOTP: "Get OTP",
  reset: "Reset",
  submit: "Submit",
  verifyAccount: "Verify Account",
  resend: "Resend",
  viewAll: "View All",
  totalBalance: "Total Balance",
  goals: "Goals",
  upcomingBills: "Upcoming Bill",
  recentTransactions: "Recent Transaction",
  statistics: "Statistics",
  expensesBreakdown: "Expenses Breakdown",
  allAccounts:"All Accounts",
};